### PR TITLE
Basic fixes to get FLEX decoder working for 3200 baud.

### LINKED ISSUE #40: FLEX decoding...almost - always loses synch
Trying to decode pager transmissions, using rtl_fm and multimon-ng on a Raspberry Pi.  This is what I've assembled from various sources, and it almost works...

rtl_fm -A fast -f 929.620M -M fm -E dc -s 22050  -F 0 | multimon-ng -n -p -t raw -a POCSAG512 -a POCSAG1200 -a POCSAG2400 -a FLEX -i -p -v 3 -f alpha  /dev/stdin

I see messages from the FLEX decoder, mostly these:

FLEX: Synchronisation Lost
FLEX: Locked
FLEX: Synchronisation Lost
FLEX: Locked

but periodically, I get:

FLEX: Locked
FLEX: SyncInfoWord: sync_code=0xd6a0 baud=3200 levels=4 polarity=NEG zero=0.013193 envelope=0.195820 symrate=1601.396648
FLEX: State: FIW
FLEX: Synchronisation Lost
FLEX: State: SYNC1
FLEX: Locked
FLEX: SyncInfoWord: sync_code=0xdea0 baud=3200 levels=4 polarity=NEG zero=0.017672 envelope=0.191791 symrate=1600.031621
FLEX: State: FIW
FLEX: Phase F Data corruption - Unable to fix errors.
FLEX: Unable to decode FIW, too much data corruption
FLEX: State: SYNC1
FLEX: Synchronisation Lost

and a few of these:

FLEX: State: FIW
FLEX: Phase F Fixed 2 errors @ 0x00084000  (0x7ffef99e -> 0x7ff6b99e)
FLEX: Bad Checksum 0x2

which seems to suggest that multimon-ng is detecting the FLEX format, and decoding some of it, but never completely successfully.  

I've played with the gain, antennas, and so on, and the results are always some variation on what you see here.

Any ideas how I might further debug this, and hopefully get it working?

### PR DESCRIPTION
**Pull request by j-dickinson**
* Decodes FIW at 1600 baud, instead of at the data rate.
* Fixes overflow of phase_rate in Flex_Demodulate when flex->Demodulator.baud is greater than 1600.
* Fixes FIW CRC calculation. See the PDW implementation for confirmation that the new algorithm is correct: https://github.com/Discriminator/PDW/blob/master/Flex.cpp#L117
* Fixes calculation of SYNC2 length.
* Fixes bug in read_data which prevented any symbols from being decoded when the baud rate wasn't 1600.
* Fixes bug in read_data which prevented certain idle patterns in phase C and phase D from being detected.

I have tested these fixes with live 1600 baud and 3200 baud 4-level signals. I have not tested them with a 1600 baud 2-level signal, but have no reason to believe that this would cause regressions in decoding those.

This fixes #40.

### CODE REVIEW

**Comment by j-dickinson** [comment]
@craigshelley, heads up about this pull request. Feel free to take a look and let me know if I missed anything.

**Comment by EliasOenal** [comment]
Thanks for looking into it! It would be nice to have some samples of FLEX at various rates, but without them the potential of regressions isn't an issue for me. If any show up, we can just fix them later.

**Comment by j-dickinson** [comment]
@EliasOenal, are you requesting that samples of FLEX be committed to the repo, or just posted for this PR? Either way it's a good idea, just wanted to clarify what you meant.

**Comment by EliasOenal** [comment]
We have an example folder in the repo. Though I'm reconsidering this, maybe we should have a separate repository for those. Since I don't have time right now, I'll merge your request next week.

**Pull request merged**
