### PR TITLE
Fixed subsampling in AFSK12, CLIPFSK, EAS, FMSFSK, UFSK12 decoders

### PR DESCRIPTION
**Pull request by luarvique**
These changes fix the subsampling algorithm in the remaining decoders which had the previous, broken algorithm. Please note that **I have no way to test these decoders**. If you have any sample input, you probably want to test the new code on that input.

### CODE REVIEW

**Comment by ramonsmits** [comment]
Can you explain what was broken? Do any bugs on the repo can be correlated?

How could I test this on the same feed? As then I could compare the output.

**Comment by luarvique** [comment]
> Can you explain what was broken? Do any bugs on the repo can be correlated?

The original subsampling algorithm was losing some data at the end, every time it was called. This is less of a problem when the algorithm is fed large portions of data, when reading from a file for example. When fed small portions data via a pipe though, things break. Namely, POCSAG512 and POCSAG1200 spew gibberish when fed via a pipe (see pull request #214).

This issue has been reported multiple times, it seems: #213 #197 #91 #70

**Comment by luarvique** [comment]
Ping? =)

**Comment by EliasOenal** [comment]
Thanks, looks good. Could you also have a look at demod_poc24.c and demod_dtmf.c? I assume they're affected as well.

**Comment by luarvique** [comment]
POCSAG2400 (demod_poc24.c) does not sub-sample. Neither does DTMF (demod_dtmf.c), as far as I can see in the code.

**Comment by EliasOenal** [comment]
Thanks for checking, I'll go ahead and merge it.

**Pull request merged**
