### PR TITLE
Update Flex Code

### PR DESCRIPTION
**Pull request by Zanoroy**
Various fixes to improve message identification and decoding.
Added Group message handling (previously being treated as UNKNOWN)

### CODE REVIEW

**Comment by Zanoroy** [comment]
Most of the updates are tracked in Issue #63

**Comment by EliasOenal** [comment]
Tell me if you want this merged as is, otherwise I'd wait until you have checked the sample of @hgisoeura.

**Comment by jklnz** [comment]
FYI it still needs one more change as it still has uint's in it

**Comment by EliasOenal** [comment]
Thanks, I'll make sure to fix this.

**Comment by Zanoroy** [comment]
I'll fix the uint after I have addressed hgisoeura sample issue and let you
know.

**Comment by EliasOenal** [comment]
So is this ready for merging?

**Comment by Zanoroy** [comment]
Yes mate.

**Comment by Zanoroy** [comment]
Cheers mate.

**Pull request merged**
